/*Things left in registration: age calculation and redirecting to user details possibly without 
having to go to login page for the first time*/
package bookapppr;

import static com.sun.org.apache.xalan.internal.lib.ExsltDatetime.year;
import java.sql.Connection;
import java.sql.*;
import java.text.ParseException;
import java.util.Date;
import java.text.SimpleDateFormat;
import java.time.LocalDate;
import java.time.Month;
import java.time.Period;
import java.util.Calendar;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author toshiba
 */
public class register extends javax.swing.JFrame {

    Connection conn=null;
    public register() {
        initComponents();
        conn=autoId.connect();
        id();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        jPasswordField1 = new javax.swing.JPasswordField();
        jPasswordField2 = new javax.swing.JPasswordField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        jTextField5 = new javax.swing.JTextField();
        jTextField6 = new javax.swing.JTextField();
        jButton4 = new javax.swing.JButton();
        jDateChooser1 = new com.toedter.calendar.JDateChooser();
        jDateChooser2 = new com.toedter.calendar.JDateChooser();
        jLabel10 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 153, 0));
        jLabel1.setText("Registration");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(240, 20, 84, 17);

        jLabel2.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        jLabel2.setText("First Name");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(130, 60, 67, 16);

        jLabel3.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        jLabel3.setText("Last Name");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(130, 90, 67, 16);

        jLabel4.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        jLabel4.setText("Mail ID");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(150, 130, 42, 16);

        jLabel5.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        jLabel5.setText("Password");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(130, 170, 62, 16);

        jLabel6.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        jLabel6.setText("Confirm password");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(80, 210, 114, 16);

        jLabel7.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        getContentPane().add(jLabel7);
        jLabel7.setBounds(191, 201, 0, 0);

        jLabel8.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        jLabel8.setText("D.O.B");
        getContentPane().add(jLabel8);
        jLabel8.setBounds(160, 250, 35, 16);

        jTextField1.setName("jTextField1"); // NOI18N
        getContentPane().add(jTextField1);
        jTextField1.setBounds(210, 50, 142, 30);

        jTextField2.setName("jTextField2"); // NOI18N
        getContentPane().add(jTextField2);
        jTextField2.setBounds(209, 87, 142, 30);

        jTextField3.setName("jTextField3"); // NOI18N
        getContentPane().add(jTextField3);
        jTextField3.setBounds(209, 123, 170, 30);

        jPasswordField1.setName("jPasswordField1"); // NOI18N
        getContentPane().add(jPasswordField1);
        jPasswordField1.setBounds(210, 160, 140, 30);

        jPasswordField2.setName("jPasswordField2"); // NOI18N
        getContentPane().add(jPasswordField2);
        jPasswordField2.setBounds(210, 200, 140, 30);

        jButton1.setLabel("Create Account");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(390, 323, 120, 30);

        jButton2.setLabel("Clear");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(310, 323, 57, 30);

        jButton3.setText("X");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3);
        jButton3.setBounds(470, 10, 50, 30);

        jLabel9.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        jLabel9.setText("ID");
        getContentPane().add(jLabel9);
        jLabel9.setBounds(180, 290, 14, 16);

        jTextField5.setName("jTextField5"); // NOI18N
        getContentPane().add(jTextField5);
        jTextField5.setBounds(210, 280, 65, 30);

        jTextField6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField6ActionPerformed(evt);
            }
        });
        getContentPane().add(jTextField6);
        jTextField6.setBounds(420, 240, 50, 30);

        jButton4.setText("Age");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton4);
        jButton4.setBounds(360, 240, 51, 30);
        getContentPane().add(jDateChooser1);
        jDateChooser1.setBounds(210, 240, 140, 30);
        getContentPane().add(jDateChooser2);
        jDateChooser2.setBounds(30, 10, 120, 30);

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/bookapppr/4c515ec047f66cec2d418c8e71b6c954.jpg"))); // NOI18N
        jLabel10.setText("jLabel2");
        getContentPane().add(jLabel10);
        jLabel10.setBounds(-50, -390, 680, 860);

        jMenu1.setText("Account");

        jMenuItem1.setText("Home");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem1);

        jMenuBar1.add(jMenu1);
        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
    jTextField1.setText("");
    jTextField2.setText("");
    jTextField3.setText("");
    jPasswordField1.setText("");
    jPasswordField2.setText("");
    jDateChooser1.setDate(null);
    jTextField5.setText("");
    jTextField5.setText("");
    }//GEN-LAST:event_jButton2ActionPerformed

   private void id(){
    try {
         String sql="SELECT ID FROM user_details ORDER BY ID DESC LIMIT 1";        
         PreparedStatement  pst=conn.prepareStatement(sql);
         ResultSet rs=pst.executeQuery();
       if(rs.next())
       {
            String rnno=rs.getString("ID");
            int co=rnno.length();
           String txt= rnno.substring(0, 2);
           String num=rnno.substring(2, co);
           int n=Integer.parseInt(num);
           n++;
           String snum=Integer.toString(n);
           String ftxt=txt+snum;
           jTextField5.setText(ftxt);

       }
       else
       {
           jTextField5.setText("10000");
       }


    } catch (Exception e) {
        JOptionPane.showMessageDialog(rootPane, e);
    }
}
    
    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
    System.exit(0);        // TODO add your handling code here:
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
    String first_name, last_name, mail_id, password, pass1;
    int ID,age;
    first_name=jTextField1.getText();
    last_name=jTextField2.getText();
    mail_id=jTextField3.getText();
    password=new String(jPasswordField1.getPassword());
    pass1=new String(jPasswordField2.getPassword());
    
        
            SimpleDateFormat dateFormat = new SimpleDateFormat("yyyy/MM/dd");
            String date_acc=dateFormat.format(jDateChooser2.getDate());
            
            String dob=dateFormat.format(jDateChooser1.getDate());
            
            ID=Integer.parseInt(jTextField5.getText());
            age=Integer.parseInt(jTextField6.getText());
    
    
        
    
    
        try {
            Class.forName("java.sql.DriverManager");
            Connection con= DriverManager.getConnection("jdbc:mysql://localhost:3306/project","root","password");
            Statement stmt= con.createStatement();
        
            String query="insert into user_details values('"+ID+"','"+first_name+"','"+last_name+"','"+mail_id+"','"+password+"','"+dob+"','"+age+"','"+date_acc+"');";
            if (!password.equals(pass1)){
                    JOptionPane.showMessageDialog(this,"Your passwords do not match!");  
                }
            else{
            stmt.executeUpdate(query);
            JOptionPane.showMessageDialog(null,"Registration completed successfully ");
            login l=new login();
            l.setVisible(true);
        
            }
              stmt.close();
              con.close();
                
                
            
            
            
            
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this,e.getMessage());
        }

    
    
    
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jTextField6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField6ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
    SimpleDateFormat dateFormat = new SimpleDateFormat("yyyy/MMMMM/dd");
            String dob=dateFormat.format(jDateChooser1.getDate());
            
            String arr[]=dob.split("/");
            int year=Integer.parseInt(arr[0]);
            Month month=(Month.valueOf(arr[1].toUpperCase()));
            int day=Integer.parseInt(arr[2]);
            
            LocalDate today=LocalDate.now();
            LocalDate birthday=LocalDate.of(year, month, day);
    
            Period p=Period.between(birthday,today);
            
            jTextField6.setText(Integer.toString(p.getYears()));
             
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
aboutpage a=new aboutpage();
a.setVisible(true);            // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(register.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(register.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(register.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(register.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new register().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private com.toedter.calendar.JDateChooser jDateChooser1;
    private com.toedter.calendar.JDateChooser jDateChooser2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JPasswordField jPasswordField1;
    private javax.swing.JPasswordField jPasswordField2;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField6;
    // End of variables declaration//GEN-END:variables
}
